// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {git} from '../models';
import {watch} from '../models';
import {stream} from '../models';
import {buildinfo} from '../models';

export function AddProject(arg1:string):Promise<project.Project>;

export function ChooseProjectDirectory():Promise<string>;

export function CreateEntry(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteEntry(arg1:string,arg2:string):Promise<void>;

export function GitBranches(arg1:string):Promise<Array<string>>;

export function GitCheckout(arg1:string,arg2:string):Promise<void>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitRemotes(arg1:string):Promise<Array<string>>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStatus(arg1:string):Promise<git.Status>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<watch.Entry>>;

export function OpenTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function Projects():Promise<Array<project.Project>>;

export function ReadFile(arg1:string,arg2:string):Promise<watch.FileContent>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StreamEndpoint():Promise<stream.Endpoint>;

export function UpdateProject(arg1:string,arg2:project.Settings):Promise<project.Project>;

export function Version():Promise<buildinfo.Info>;

export function WriteFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
