// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['app']['App']['AddProject'](arg1);
}

export function ChooseProjectDirectory() {
  return window['go']['app']['App']['ChooseProjectDirectory']();
}

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1, arg2) {
  return window['go']['app']['App']['DeleteEntry'](arg1, arg2);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['app']['App']['ListDirectory'](arg1, arg2);
}

export function OpenTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenTerminal'](arg1, arg2, arg3);
}

export function Projects() {
  return window['go']['app']['App']['Projects']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['app']['App']['ReadFile'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['app']['App']['RemoveProject'](arg1);
}

export function RenameEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameEntry'](arg1, arg2, arg3);
}

export function StreamEndpoint() {
  return window['go']['app']['App']['StreamEndpoint']();
}

export function UpdateProject(arg1, arg2) {
  return window['go']['app']['App']['UpdateProject'](arg1, arg2);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}

export function WriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2, arg3, arg4);
}
