// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['app']['App']['AddProject'](arg1, arg2);
}

export function BindFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['BindFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function ChooseProjectDirectory() {
  return window['go']['app']['App']['ChooseProjectDirectory']();
}

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1, arg2) {
  return window['go']['app']['App']['DeleteEntry'](arg1, arg2);
}

export function GitBlame(arg1, arg2) {
  return window['go']['app']['App']['GitBlame'](arg1, arg2);
}

export function GitBranches(arg1) {
  return window['go']['app']['App']['GitBranches'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['app']['App']['GitCheckout'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['app']['App']['GitPull'](arg1);
}

export function GitPush(arg1, arg2, arg3) {
  return window['go']['app']['App']['GitPush'](arg1, arg2, arg3);
}

export function GitRemotes(arg1) {
  return window['go']['app']['App']['GitRemotes'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['app']['App']['GitStatus'](arg1);
}

export function KubeBinding(arg1, arg2) {
  return window['go']['app']['App']['KubeBinding'](arg1, arg2);
}

export function KubeCheck(arg1, arg2) {
  return window['go']['app']['App']['KubeCheck'](arg1, arg2);
}

export function KubeContexts() {
  return window['go']['app']['App']['KubeContexts']();
}

export function KubeNamespaces(arg1) {
  return window['go']['app']['App']['KubeNamespaces'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['app']['App']['ListDirectory'](arg1, arg2);
}

export function OpenTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenTerminal'](arg1, arg2, arg3);
}

export function Projects() {
  return window['go']['app']['App']['Projects']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['app']['App']['ReadFile'](arg1, arg2);
}

export function ReadPrefixes(arg1, arg2) {
  return window['go']['app']['App']['ReadPrefixes'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['app']['App']['RemoveProject'](arg1);
}

export function RenameEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameEntry'](arg1, arg2, arg3);
}

export function ReorderProjects(arg1) {
  return window['go']['app']['App']['ReorderProjects'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SessionState() {
  return window['go']['app']['App']['SessionState']();
}

export function StreamEndpoint() {
  return window['go']['app']['App']['StreamEndpoint']();
}

export function Tools() {
  return window['go']['app']['App']['Tools']();
}

export function UnbindFolder(arg1, arg2) {
  return window['go']['app']['App']['UnbindFolder'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['app']['App']['UpdateProject'](arg1, arg2);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}

export function WriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2, arg3, arg4);
}
