// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenTerminal'](arg1, arg2, arg3);
}

export function StreamEndpoint() {
  return window['go']['app']['App']['StreamEndpoint']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
